### ISSUE TITLE
proper closing with multiple queues

### ISSUE THREAD

**Issue by heycalmdown** [gmr/rabbitpy#117]
I need multiple threads to consume multiple queues. Channels can not be shared through threads, so the each thread should make their own.

```py
def thread_rpc_queue(connection, queueName):
    with connection.channel() as ch:
        q = rabbitpy.Queue(ch, queueName)
        q.declare()

        for msg in q:
            print('yay')
            msg.ack()


for i in range(10):
    t = threading.Thread(target=thread_rpc_queue, kwargs={'connection': conn, 'queueName': 'q.' + str(i)})
    t.start()
```

But because of `conn.close()` will delete its channels in the main thread, I'm getting several errors like by random;

* `rabbitpy.exceptions.ChannelClosedException: Can not perform RPC requests on a closed channel, you must create a new channel`
* `rabbitpy.exceptions.ConnectionClosed: The connection is closed`
* `RuntimeError: dictionary changed size during iteration`

Could you give me some advice how to handle multiple queues and close properly?

**Comment by DanSchum** [comment]
Good question. Facing similar problem. Any updates?

**Comment by gmr** [comment]
Create the connection directly without using it as a context manager:

```python
conn = rabbitpy.Connection(...)
```
Then pass that in your threads and create your channel in the thread.

**Comment by DanSchum** [comment]
I saved all my active queues (from different threads) and before closing the connection I cancel the consuming of these queue gracefully. This works pretty good for me.
