### ISSUE TITLE
Support for pamqp>=2.0.0

### ISSUE THREAD

**Issue by knedlsepp** [gmr/rabbitpy#118]
Now that pamqp 2.0.0 is out, but `setup.py` still states that it's unsupported, I was wondering if there are any known issues.

**Comment by NathanUrwin** [comment]
Any status on this? Trying to use [pytest-rabbitmq](https://github.com/ClearcodeHQ/pytest-rabbitmq) and [aio-pika](https://github.com/mosquito/aio-pika) together, but this package is holding me back!

**Comment by gmr** [comment]
I'm in the process of readying pamqp 2.2.0 and will update rabbitpy when that drops.

**Comment by NathanUrwin** [comment]
Hey @gmr 👋  Thanks for the quick reply!

I just wrote a quick-and-dirty rabbitmq pytest fixture that uses subprocess and docker under the hood, so no worries. I would definitely prefer to use pytest-rabbitmq though.

That sounds great. Looking forward to it! 😄

**Comment by gmr** [comment]
2.0.0 was released and pushed to pypi today. It's worth noting that it has a breaking behavior of changing the type of field-table values from bytes to str.
