### ISSUE TITLE
Headers keys are always raw bytes and never strings when running on python 3

### ISSUE THREAD

**Issue by Gyllsdorff** [gmr/rabbitpy#51]
This might be intentional but in that case it should probably be mentioned somewhere in the documentation.

Right now we have to remember to put a `b` before the string key every time we try to access a header value while running python 3.

``` python
message.properties.get('headers').get(b'foo').decode()
```

The same thing applies to the `message.properties` values. They are always raw bytes and never Strings even if the field description is `short_str`

The problem seems to be in pamqp [decode.py:370, _maybe_utf8()](https://github.com/gmr/pamqp/blob/master/pamqp/decode.py#L370). 

When `_maybe_utf8` is called while running python 3 it will **always** return bytes and never str or unicode. Since `_maybe_utf8` is used while decoding table keys it also causes the header keys to be bytes.

**Comment by gmr** [comment]
I believe this issue is addressed with newer versions of pamqp.
