### ISSUE TITLE
Cannot connect to a server with channel_max == 65535

### ISSUE THREAD

**Issue by carlhoerberg** [gmr/rabbitpy#62]
If the server has configured channel_max 65536 (instead of the default 0) rabbitpy can't connect. A bug in the channel_max negotiation code?

**Comment by gmr** [comment]
You're exceeding the maximum number of channels in the AMQP spec. It's an unsigned short int (max of 65535).

**Comment by carlhoerberg** [comment]
Sorry, typo, it is configured to 65535.

**Comment by gmr** [comment]
Looks like a bug in the guard code in pamqp. I'm testing a fix for it bumping from 1.6.0 to 1.6.1.

**Comment by carlhoerberg** [comment]
Set `rabbitmqctl eval 'application:set_env(rabbit, channel_max, 65535).'`and try connect

**Comment by gmr** [comment]
https://github.com/gmr/pamqp/commit/202123c69f9ea1ee516f11f43a5e39fbe630d736

**Comment by gmr** [comment]
pamqp 1.6.1 has been released which should address your issue (Assuming you're getting a ``TypeError`` when trying to connect). Please confirm if this indeed addresses your issue.

**Comment by gmr** [comment]
@carlhoerberg did you get a chance to see if 1.6.1 addressed your issue?

**Comment by gmr** [comment]
Closing, please reopen if this is not addressed (I believe it is)
