### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by jtillman** [gmr/rabbitpy#65]
I've seen changes and a version bump to 0.26.0 but I haven't yet seen the release public. Was this intentional? I was hoping to get a couple of those changes.

**Comment by gmr** [comment]
Will be dropping soon.

**Comment by jtillman** [comment]
Awesome, Thanks

**Comment by gmr** [comment]
0.26.1 is now up on pypi. Thanks for the nudge and changes that made it into this version.
