### ISSUE TITLE
heartbeat can not be set to 0

### ISSUE THREAD

**Issue by michaelplaing** [gmr/rabbitpy#69]
The internal logic treats 0 as None and sets the default instead. There is no workaround I can see except to set heartbeat to a ridiculously high number.

The real problem however is that my apps are getting heartbeat exceptions even tho there is traffic on the connection. RabbitMQ 3.5.1, python 2.7.9 on Amazon Linux, local connection between client and server.

I believe this is because there has been other traffic sent on the connection during the interval, hence no heartbeat is sent by the server on channel 0. I am checking w Pivotal to confirm my understanding of server behavior.

**Comment by michaelplaing** [comment]
Oh actually the logic looks OK - I missed a paren - I'll investigate more and comment again.

**Comment by michaelplaing** [comment]
Ah - the logic in Channel0._negotiate is the culprit:
`return min(client_value, server_value) or (client_value or server_value)`
will never return a 0 for heartbeat.

**Comment by michaelplaing** [comment]
Still leaving the real problem however...

**Comment by michaelplaing** [comment]
And the same logic prevents the 'ridiculously high number' workaround - hmmm.

**Comment by gmr** [comment]
I'll look into this ASAP.

**Comment by michaelplaing** [comment]
Thanks!

**Comment by gmr** [comment]
I'll release the a new version ASAP (likely tonight)
