### ISSUE TITLE
queue.consume seems to lock after all messages consumed, then new jobs added

### ISSUE THREAD

**Issue by dubmartin** [gmr/rabbitpy#75]
```
for message in queue.consume():
                    self.taskLogger.info("Got message off queue")

                    self.handleMessage(message)
                    self.taskLogger.info("completed handle message")

self.taskLogger.info("consumed all messages")
```

I am unsure exactly, but once all messages are handled and the queue is 0, if any new messages are added, no more messages are received. It is as if the queue is locked or lost connection or something

I recently updated to the latest version via pip due to a similar issue happening if the rabbitmq server went down, but this isn't the cause of this issue, as the rabbitmq hasn't gone down

**Comment by dubmartin** [comment]
forgot to add, no exceptions are thrown from rabbit py, after the last message is consumed, the last log is "completed handle messge", then nothing, new jobs added but nothing happens

**Comment by gmr** [comment]
And you're acking the message? it appears you're not using no_ack... that's a weird behavior for sure. Are you able to provide a repeatable test case (as existing use and test cases do not show this behavior).

**Comment by dubmartin** [comment]
>And you're acking the message? it appears you're not using no_ack
Yes that happens in the 
```
self.handleMessage()
```

It is basically a 
try...
  ack
except...
    nack


>Are you able to provide a repeatable test case (as existing use and test cases do not show this behavior).

I will try, but I doubt. The project has 3 similar queues, the other two are fine. The code is also duplicate on a test server and works. Of course, the issue is on the production server which makes running tests on it difficult.

I fully expect the issue to be my fault somewhere, so really looking for suggestions on how to go about trying to debug this

**Comment by gmr** [comment]
Can you please try and test this against the current master? I've reworked heartbeat handling and a few other things that touch this code path.

**Comment by dubmartin** [comment]
Been running a couple of days with the master and no more issue. So whatever the issue was, appears to be fixed.

Many thanks
